# Generated by Django 5.1.7 on 2025-03-20 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('marital_status', models.CharField(choices=[('NM', 'Never Married'), ('DIV', 'Divorced'), ('WID', 'Widowed'), ('SEP', 'Separated')], max_length=3)),
                ('about_me', models.TextField(blank=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pics')),
                ('height', models.IntegerField(help_text='Height in centimeters')),
                ('body_type', models.CharField(blank=True, max_length=50)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('religion', models.CharField(max_length=100)),
                ('mother_tongue', models.CharField(max_length=100)),
                ('community', models.CharField(blank=True, max_length=100)),
                ('education', models.CharField(max_length=200)),
                ('occupation', models.CharField(max_length=200)),
                ('income', models.CharField(blank=True, max_length=50)),
                ('family_type', models.CharField(blank=True, max_length=50)),
                ('family_status', models.CharField(blank=True, max_length=50)),
                ('family_values', models.CharField(blank=True, max_length=50)),
                ('diet', models.CharField(blank=True, max_length=50)),
                ('smoking', models.CharField(blank=True, max_length=50)),
                ('drinking', models.CharField(blank=True, max_length=50)),
                ('partner_age_min', models.IntegerField(default=18)),
                ('partner_age_max', models.IntegerField(default=65)),
                ('partner_height_min', models.IntegerField(default=150, help_text='Height in centimeters')),
                ('partner_height_max', models.IntegerField(default=200, help_text='Height in centimeters')),
                ('partner_religion_preference', models.CharField(blank=True, max_length=200)),
                ('partner_education_preference', models.CharField(blank=True, max_length=200)),
                ('partner_occupation_preference', models.CharField(blank=True, max_length=200)),
                ('other_preferences', models.TextField(blank=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
